stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the webpage..."

test_job:
  stage: test
  script:
    - echo "Running tests..."

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the webpage..."
    # Add commands here to deploy the webpage to your desired hosting platform
